/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * MasterArea generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`master_area`")
public class MasterArea implements Serializable {

    private Integer id;
    private String areaCode;
    private Integer remoId;
    private String areaName;
    private RemoRegions remoRegions;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "`master_area_id_seq`" , allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`area_code`", nullable = true, length = 255)
    public String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    @Column(name = "`remo_id`", nullable = true, scale = 0, precision = 10)
    public Integer getRemoId() {
        return this.remoId;
    }

    public void setRemoId(Integer remoId) {
        this.remoId = remoId;
    }

    @Column(name = "`area_name`", nullable = true, length = 255)
    public String getAreaName() {
        return this.areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`remo_id`", referencedColumnName = "`id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_master_area_TO_remo_r7oFnm`"))
    @Fetch(FetchMode.JOIN)
    public RemoRegions getRemoRegions() {
        return this.remoRegions;
    }

    public void setRemoRegions(RemoRegions remoRegions) {
        if(remoRegions != null) {
            this.remoId = remoRegions.getId();
        }

        this.remoRegions = remoRegions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof MasterArea)) return false;
        final MasterArea masterArea = (MasterArea) o;
        return Objects.equals(getId(), masterArea.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}