/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class PaymentScheduleId implements Serializable {

    private String noAggr;
    private Integer noInst;

    public String getNoAggr() {
        return this.noAggr;
    }

    public void setNoAggr(String noAggr) {
        this.noAggr = noAggr;
    }

    public Integer getNoInst() {
        return this.noInst;
    }

    public void setNoInst(Integer noInst) {
        this.noInst = noInst;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PaymentSchedule)) return false;
        final PaymentSchedule paymentSchedule = (PaymentSchedule) o;
        return Objects.equals(getNoAggr(), paymentSchedule.getNoAggr()) &&
                Objects.equals(getNoInst(), paymentSchedule.getNoInst());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNoAggr(),
                getNoInst());
    }
}