/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Pools generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`pools`")
public class Pools implements Serializable {

    private Integer id;
    private String cdWarehouse;
    private String descWarehouse;
    private String city;
    private String postCode;
    private Date dateAdded;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "`pools_id_seq`" , allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`cd_warehouse`", nullable = true, length = 3)
    public String getCdWarehouse() {
        return this.cdWarehouse;
    }

    public void setCdWarehouse(String cdWarehouse) {
        this.cdWarehouse = cdWarehouse;
    }

    @Column(name = "`desc_warehouse`", nullable = true, length = 255)
    public String getDescWarehouse() {
        return this.descWarehouse;
    }

    public void setDescWarehouse(String descWarehouse) {
        this.descWarehouse = descWarehouse;
    }

    @Column(name = "`city`", nullable = true, length = 255)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "`post_code`", nullable = true, length = 255)
    public String getPostCode() {
        return this.postCode;
    }

    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    @Column(name = "`date_added`", nullable = true)
    public Date getDateAdded() {
        return this.dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Pools)) return false;
        final Pools pools = (Pools) o;
        return Objects.equals(getId(), pools.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}