/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetAllUsersRemoResponse implements Serializable {


    @ColumnAlias("full_name")
    private String fullName;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("role_type")
    private String roleType;

    @ColumnAlias("province")
    private String province;

    @ColumnAlias("city")
    private String city;

    @ColumnAlias("status")
    private String status;

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRoleType() {
        return this.roleType;
    }

    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetAllUsersRemoResponse)) return false;
        final GetAllUsersRemoResponse getAllUsersRemoResponse = (GetAllUsersRemoResponse) o;
        return Objects.equals(getFullName(), getAllUsersRemoResponse.getFullName()) &&
                Objects.equals(getEmail(), getAllUsersRemoResponse.getEmail()) &&
                Objects.equals(getRoleType(), getAllUsersRemoResponse.getRoleType()) &&
                Objects.equals(getProvince(), getAllUsersRemoResponse.getProvince()) &&
                Objects.equals(getCity(), getAllUsersRemoResponse.getCity()) &&
                Objects.equals(getStatus(), getAllUsersRemoResponse.getStatus());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFullName(),
                getEmail(),
                getRoleType(),
                getProvince(),
                getCity(),
                getStatus());
    }
}