/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetLelangSkdetailByRemoIdResponse implements Serializable {


    @ColumnAlias("nomor_agreement")
    private String nomorAgreement;

    @ColumnAlias("judul")
    private String judul;

    @ColumnAlias("batas_bto")
    private Integer batasBto;

    @ColumnAlias("tawaran_terendah")
    private Integer tawaranTerendah;

    public String getNomorAgreement() {
        return this.nomorAgreement;
    }

    public void setNomorAgreement(String nomorAgreement) {
        this.nomorAgreement = nomorAgreement;
    }

    public String getJudul() {
        return this.judul;
    }

    public void setJudul(String judul) {
        this.judul = judul;
    }

    public Integer getBatasBto() {
        return this.batasBto;
    }

    public void setBatasBto(Integer batasBto) {
        this.batasBto = batasBto;
    }

    public Integer getTawaranTerendah() {
        return this.tawaranTerendah;
    }

    public void setTawaranTerendah(Integer tawaranTerendah) {
        this.tawaranTerendah = tawaranTerendah;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetLelangSkdetailByRemoIdResponse)) return false;
        final GetLelangSkdetailByRemoIdResponse getLelangSkdetailByRemoIdResponse = (GetLelangSkdetailByRemoIdResponse) o;
        return Objects.equals(getNomorAgreement(), getLelangSkdetailByRemoIdResponse.getNomorAgreement()) &&
                Objects.equals(getJudul(), getLelangSkdetailByRemoIdResponse.getJudul()) &&
                Objects.equals(getBatasBto(), getLelangSkdetailByRemoIdResponse.getBatasBto()) &&
                Objects.equals(getTawaranTerendah(), getLelangSkdetailByRemoIdResponse.getTawaranTerendah());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNomorAgreement(),
                getJudul(),
                getBatasBto(),
                getTawaranTerendah());
    }
}