/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetLelangTidakAktifResponse implements Serializable {


    @ColumnAlias("number")
    private Integer number;

    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("area")
    private String area;

    @ColumnAlias("start_date")
    private Timestamp startDate;

    @ColumnAlias("end_date")
    private Timestamp endDate;

    @ColumnAlias("title")
    private String title;

    @ColumnAlias("detil_id")
    private Integer detilId;

    @ColumnAlias("area_name")
    private String areaName;

    @ColumnAlias("agreement_no")
    private String agreementNo;

    @ColumnAlias("bto_limit")
    private Integer btoLimit;

    @ColumnAlias("lowest_bid")
    private Integer lowestBid;

    @ColumnAlias("description")
    private String description;

    @ColumnAlias("winner_name")
    private String winnerName;

    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public Timestamp getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    public Timestamp getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Timestamp endDate) {
        this.endDate = endDate;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getDetilId() {
        return this.detilId;
    }

    public void setDetilId(Integer detilId) {
        this.detilId = detilId;
    }

    public String getAreaName() {
        return this.areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getAgreementNo() {
        return this.agreementNo;
    }

    public void setAgreementNo(String agreementNo) {
        this.agreementNo = agreementNo;
    }

    public Integer getBtoLimit() {
        return this.btoLimit;
    }

    public void setBtoLimit(Integer btoLimit) {
        this.btoLimit = btoLimit;
    }

    public Integer getLowestBid() {
        return this.lowestBid;
    }

    public void setLowestBid(Integer lowestBid) {
        this.lowestBid = lowestBid;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getWinnerName() {
        return this.winnerName;
    }

    public void setWinnerName(String winnerName) {
        this.winnerName = winnerName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetLelangTidakAktifResponse)) return false;
        final GetLelangTidakAktifResponse getLelangTidakAktifResponse = (GetLelangTidakAktifResponse) o;
        return Objects.equals(getNumber(), getLelangTidakAktifResponse.getNumber()) &&
                Objects.equals(getId(), getLelangTidakAktifResponse.getId()) &&
                Objects.equals(getArea(), getLelangTidakAktifResponse.getArea()) &&
                Objects.equals(getStartDate(), getLelangTidakAktifResponse.getStartDate()) &&
                Objects.equals(getEndDate(), getLelangTidakAktifResponse.getEndDate()) &&
                Objects.equals(getTitle(), getLelangTidakAktifResponse.getTitle()) &&
                Objects.equals(getDetilId(), getLelangTidakAktifResponse.getDetilId()) &&
                Objects.equals(getAreaName(), getLelangTidakAktifResponse.getAreaName()) &&
                Objects.equals(getAgreementNo(), getLelangTidakAktifResponse.getAgreementNo()) &&
                Objects.equals(getBtoLimit(), getLelangTidakAktifResponse.getBtoLimit()) &&
                Objects.equals(getLowestBid(), getLelangTidakAktifResponse.getLowestBid()) &&
                Objects.equals(getDescription(), getLelangTidakAktifResponse.getDescription()) &&
                Objects.equals(getWinnerName(), getLelangTidakAktifResponse.getWinnerName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNumber(),
                getId(),
                getArea(),
                getStartDate(),
                getEndDate(),
                getTitle(),
                getDetilId(),
                getAreaName(),
                getAgreementNo(),
                getBtoLimit(),
                getLowestBid(),
                getDescription(),
                getWinnerName());
    }
}