/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetReportListByNoAggrResponse implements Serializable {


    @ColumnAlias("number")
    private Integer number;

    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("vehicle_no_aggr")
    private String vehicleNoAggr;

    @ColumnAlias("description")
    private String description;

    @ColumnAlias("latitude")
    private BigDecimal latitude;

    @ColumnAlias("longitute")
    private BigDecimal longitute;

    @ColumnAlias("is_draft")
    private Boolean isDraft;

    @ColumnAlias("created_at")
    private Timestamp createdAt;

    @ColumnAlias("created_by")
    private String createdBy;

    @ColumnAlias("updated_at")
    private Timestamp updatedAt;

    @ColumnAlias("updated_by")
    private String updatedBy;

    @ColumnAlias("deleted_at")
    private Timestamp deletedAt;

    @ColumnAlias("deleted_by")
    private String deletedBy;

    @ColumnAlias("image_header")
    private String imageHeader;

    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getVehicleNoAggr() {
        return this.vehicleNoAggr;
    }

    public void setVehicleNoAggr(String vehicleNoAggr) {
        this.vehicleNoAggr = vehicleNoAggr;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getLatitude() {
        return this.latitude;
    }

    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    public BigDecimal getLongitute() {
        return this.longitute;
    }

    public void setLongitute(BigDecimal longitute) {
        this.longitute = longitute;
    }

    public Boolean getIsDraft() {
        return this.isDraft;
    }

    public void setIsDraft(Boolean isDraft) {
        this.isDraft = isDraft;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Timestamp deletedAt) {
        this.deletedAt = deletedAt;
    }

    public String getDeletedBy() {
        return this.deletedBy;
    }

    public void setDeletedBy(String deletedBy) {
        this.deletedBy = deletedBy;
    }

    public String getImageHeader() {
        return this.imageHeader;
    }

    public void setImageHeader(String imageHeader) {
        this.imageHeader = imageHeader;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetReportListByNoAggrResponse)) return false;
        final GetReportListByNoAggrResponse getReportListByNoAggrResponse = (GetReportListByNoAggrResponse) o;
        return Objects.equals(getNumber(), getReportListByNoAggrResponse.getNumber()) &&
                Objects.equals(getId(), getReportListByNoAggrResponse.getId()) &&
                Objects.equals(getVehicleNoAggr(), getReportListByNoAggrResponse.getVehicleNoAggr()) &&
                Objects.equals(getDescription(), getReportListByNoAggrResponse.getDescription()) &&
                Objects.equals(getLatitude(), getReportListByNoAggrResponse.getLatitude()) &&
                Objects.equals(getLongitute(), getReportListByNoAggrResponse.getLongitute()) &&
                Objects.equals(getIsDraft(), getReportListByNoAggrResponse.getIsDraft()) &&
                Objects.equals(getCreatedAt(), getReportListByNoAggrResponse.getCreatedAt()) &&
                Objects.equals(getCreatedBy(), getReportListByNoAggrResponse.getCreatedBy()) &&
                Objects.equals(getUpdatedAt(), getReportListByNoAggrResponse.getUpdatedAt()) &&
                Objects.equals(getUpdatedBy(), getReportListByNoAggrResponse.getUpdatedBy()) &&
                Objects.equals(getDeletedAt(), getReportListByNoAggrResponse.getDeletedAt()) &&
                Objects.equals(getDeletedBy(), getReportListByNoAggrResponse.getDeletedBy()) &&
                Objects.equals(getImageHeader(), getReportListByNoAggrResponse.getImageHeader());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNumber(),
                getId(),
                getVehicleNoAggr(),
                getDescription(),
                getLatitude(),
                getLongitute(),
                getIsDraft(),
                getCreatedAt(),
                getCreatedBy(),
                getUpdatedAt(),
                getUpdatedBy(),
                getDeletedAt(),
                getDeletedBy(),
                getImageHeader());
    }
}