/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetSkrequestPerpanjangPendingListResponse implements Serializable {


    @ColumnAlias("number")
    private Integer number;

    @ColumnAlias("name")
    private String name;

    @ColumnAlias("no_sr")
    private Integer noSr;

    @ColumnAlias("no_aggr")
    private String noAggr;

    @ColumnAlias("no_police")
    private String noPolice;

    @ColumnAlias("no_sp_coll")
    private String noSpColl;

    @ColumnAlias("coll_cd")
    private String collCd;

    @ColumnAlias("req_sk_bt")
    private Long reqSkBt;

    @ColumnAlias("req_sk_date")
    private Timestamp reqSkDate;

    @ColumnAlias("flag_sk")
    private String flagSk;

    @ColumnAlias("flag_econtract")
    private String flagEcontract;

    @ColumnAlias("flag_fidusia")
    private String flagFidusia;

    @ColumnAlias("flag_trnschedule")
    private String flagTrnschedule;

    @ColumnAlias("flag_digisign")
    private String flagDigisign;

    @ColumnAlias("app_date")
    private Timestamp appDate;

    @ColumnAlias("add_uid")
    private String addUid;

    @ColumnAlias("add_date")
    private Date addDate;

    @ColumnAlias("status")
    private Short status;

    @ColumnAlias("sk_parent")
    private Integer skParent;

    @ColumnAlias("is_show")
    private Boolean isShow;

    @ColumnAlias("app_sk_bt")
    private Long appSkBt;

    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getNoSr() {
        return this.noSr;
    }

    public void setNoSr(Integer noSr) {
        this.noSr = noSr;
    }

    public String getNoAggr() {
        return this.noAggr;
    }

    public void setNoAggr(String noAggr) {
        this.noAggr = noAggr;
    }

    public String getNoPolice() {
        return this.noPolice;
    }

    public void setNoPolice(String noPolice) {
        this.noPolice = noPolice;
    }

    public String getNoSpColl() {
        return this.noSpColl;
    }

    public void setNoSpColl(String noSpColl) {
        this.noSpColl = noSpColl;
    }

    public String getCollCd() {
        return this.collCd;
    }

    public void setCollCd(String collCd) {
        this.collCd = collCd;
    }

    public Long getReqSkBt() {
        return this.reqSkBt;
    }

    public void setReqSkBt(Long reqSkBt) {
        this.reqSkBt = reqSkBt;
    }

    public Timestamp getReqSkDate() {
        return this.reqSkDate;
    }

    public void setReqSkDate(Timestamp reqSkDate) {
        this.reqSkDate = reqSkDate;
    }

    public String getFlagSk() {
        return this.flagSk;
    }

    public void setFlagSk(String flagSk) {
        this.flagSk = flagSk;
    }

    public String getFlagEcontract() {
        return this.flagEcontract;
    }

    public void setFlagEcontract(String flagEcontract) {
        this.flagEcontract = flagEcontract;
    }

    public String getFlagFidusia() {
        return this.flagFidusia;
    }

    public void setFlagFidusia(String flagFidusia) {
        this.flagFidusia = flagFidusia;
    }

    public String getFlagTrnschedule() {
        return this.flagTrnschedule;
    }

    public void setFlagTrnschedule(String flagTrnschedule) {
        this.flagTrnschedule = flagTrnschedule;
    }

    public String getFlagDigisign() {
        return this.flagDigisign;
    }

    public void setFlagDigisign(String flagDigisign) {
        this.flagDigisign = flagDigisign;
    }

    public Timestamp getAppDate() {
        return this.appDate;
    }

    public void setAppDate(Timestamp appDate) {
        this.appDate = appDate;
    }

    public String getAddUid() {
        return this.addUid;
    }

    public void setAddUid(String addUid) {
        this.addUid = addUid;
    }

    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    public Short getStatus() {
        return this.status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Integer getSkParent() {
        return this.skParent;
    }

    public void setSkParent(Integer skParent) {
        this.skParent = skParent;
    }

    public Boolean getIsShow() {
        return this.isShow;
    }

    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    public Long getAppSkBt() {
        return this.appSkBt;
    }

    public void setAppSkBt(Long appSkBt) {
        this.appSkBt = appSkBt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetSkrequestPerpanjangPendingListResponse)) return false;
        final GetSkrequestPerpanjangPendingListResponse getSkrequestPerpanjangPendingListResponse = (GetSkrequestPerpanjangPendingListResponse) o;
        return Objects.equals(getNumber(), getSkrequestPerpanjangPendingListResponse.getNumber()) &&
                Objects.equals(getName(), getSkrequestPerpanjangPendingListResponse.getName()) &&
                Objects.equals(getNoSr(), getSkrequestPerpanjangPendingListResponse.getNoSr()) &&
                Objects.equals(getNoAggr(), getSkrequestPerpanjangPendingListResponse.getNoAggr()) &&
                Objects.equals(getNoPolice(), getSkrequestPerpanjangPendingListResponse.getNoPolice()) &&
                Objects.equals(getNoSpColl(), getSkrequestPerpanjangPendingListResponse.getNoSpColl()) &&
                Objects.equals(getCollCd(), getSkrequestPerpanjangPendingListResponse.getCollCd()) &&
                Objects.equals(getReqSkBt(), getSkrequestPerpanjangPendingListResponse.getReqSkBt()) &&
                Objects.equals(getReqSkDate(), getSkrequestPerpanjangPendingListResponse.getReqSkDate()) &&
                Objects.equals(getFlagSk(), getSkrequestPerpanjangPendingListResponse.getFlagSk()) &&
                Objects.equals(getFlagEcontract(), getSkrequestPerpanjangPendingListResponse.getFlagEcontract()) &&
                Objects.equals(getFlagFidusia(), getSkrequestPerpanjangPendingListResponse.getFlagFidusia()) &&
                Objects.equals(getFlagTrnschedule(), getSkrequestPerpanjangPendingListResponse.getFlagTrnschedule()) &&
                Objects.equals(getFlagDigisign(), getSkrequestPerpanjangPendingListResponse.getFlagDigisign()) &&
                Objects.equals(getAppDate(), getSkrequestPerpanjangPendingListResponse.getAppDate()) &&
                Objects.equals(getAddUid(), getSkrequestPerpanjangPendingListResponse.getAddUid()) &&
                Objects.equals(getAddDate(), getSkrequestPerpanjangPendingListResponse.getAddDate()) &&
                Objects.equals(getStatus(), getSkrequestPerpanjangPendingListResponse.getStatus()) &&
                Objects.equals(getSkParent(), getSkrequestPerpanjangPendingListResponse.getSkParent()) &&
                Objects.equals(getIsShow(), getSkrequestPerpanjangPendingListResponse.getIsShow()) &&
                Objects.equals(getAppSkBt(), getSkrequestPerpanjangPendingListResponse.getAppSkBt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNumber(),
                getName(),
                getNoSr(),
                getNoAggr(),
                getNoPolice(),
                getNoSpColl(),
                getCollCd(),
                getReqSkBt(),
                getReqSkDate(),
                getFlagSk(),
                getFlagEcontract(),
                getFlagFidusia(),
                getFlagTrnschedule(),
                getFlagDigisign(),
                getAppDate(),
                getAddUid(),
                getAddDate(),
                getStatus(),
                getSkParent(),
                getIsShow(),
                getAppSkBt());
    }
}