/*Copyright (c) 2019-2020 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.acc_hunter_web.acc_hunter.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetUserParticipantLelangResponse implements Serializable {


    @ColumnAlias("cd_coll")
    private String cdColl;

    @ColumnAlias("full_name")
    private String fullName;

    public String getCdColl() {
        return this.cdColl;
    }

    public void setCdColl(String cdColl) {
        this.cdColl = cdColl;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetUserParticipantLelangResponse)) return false;
        final GetUserParticipantLelangResponse getUserParticipantLelangResponse = (GetUserParticipantLelangResponse) o;
        return Objects.equals(getCdColl(), getUserParticipantLelangResponse.getCdColl()) &&
                Objects.equals(getFullName(), getUserParticipantLelangResponse.getFullName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCdColl(),
                getFullName());
    }
}